export const kols = [
  { id: "UCwDBDW_zegBNl9BAWI3tyjw", title: "阿萬", category: [1, 3, 12] },
  { id: "UCCSGfsiVc5DRzxwohAf6uIw", title: "Cqi西區", category: [2, 5] },
  { id: "UCdiKkZUr0HoKHrCrOp4rnCw", title: "簡單人生", category: [15] },
  { id: "UCuaFZMS5b1IfBtcfaYgiBAQ", title: "奈子伽", category: [7, 9] },
  { id: "UCdS9DTnkhePAZrf55njN1fw", title: "索神CABLE", category: [6, 18] },
  { id: "UCF3Aleqa9GTr1xCG1S9vMPA", title: "Deoud", category: [1] },
  {
    id: "UCIOUJ9kLEqpqM9c07RLeTpw",
    title: "睡大 Still_Sleepy",
    category: [8, 11],
  },

  {
    id: "UC5QjZTni0OGnoxYts4_px4w",
    title: "豬豬與綿綿o",
    category: [1, 3, 12],
  },
  { id: "UCXsPoqlTBlZt1rFqOxlvGlw", title: "陳小鬼", category: [1] },
  { id: "UCjuGE-58IKStZMFZK08a3YQ", title: "Tony大木", category: [4] },
  { id: "UCE-A7ThGzDGjA7AkwrjV1ww", title: "教練Coach", category: [7, 11] },
  { id: "UC7rMp-DmU9jfViQNM3wVtkQ", title: "鶻先生", category: [10, 19] },
];

export const categories = [
  { id: 1, name: "遊戲" },
  { id: 2, name: "美妝時尚" },
  { id: 3, name: "插畫" },
  { id: 4, name: "財經" },
  { id: 5, name: "感情關係" },
  { id: 6, name: "音樂" },
  { id: 7, name: "手作藝文" },
  { id: 8, name: "生活綜合" },
  { id: 9, name: "旅遊" },
  { id: 10, name: "運動" },
  { id: 11, name: "知識" },
  { id: 12, name: "3C攝影" },
  { id: 13, name: "影劇" },
  { id: 14, name: "汽機車" },
  { id: 15, name: "美食" },
  { id: 16, name: "親子" },
  { id: 17, name: "異國" },
  { id: 18, name: "料理" },
  { id: 19, name: "寵物" },
  { id: 20, name: "命理" },
  { id: 21, name: "魔術" },
];
