export const H55TEAM_LIST_REQUEST = "H55TEAM_LIST_REQUEST";
export const H55TEAM_LIST_SUCCESS = "H55TEAM_LIST_SUCCESS";
export const H55TEAM_LIST_FAIL = "H55TEAM_LIST_FAIL";
export const H55TEAM_LIST_RESET = "H55TEAM_LIST_RESET";

export const H55MATCH_LIST_REQUEST = "H55MATCH_LIST_REQUEST";
export const H55MATCH_LIST_SUCCESS = "H55MATCH_LIST_SUCCESS";
export const H55MATCH_LIST_FAIL = "H55MATCH_LIST_FAIL";
export const H55MATCH_LIST_RESET = "H55MATCH_LIST_RESET";
