export const H55TEAM_LIST_REQUEST = "H55TEAM_LIST_REQUEST";
export const H55TEAM_LIST_SUCCESS = "H55TEAM_LIST_SUCCESS";
export const H55TEAM_LIST_FAIL = "H55TEAM_LIST_FAIL";
export const H55TEAM_LIST_RESET = "H55TEAM_LIST_RESET";

export const H55MATCH_LIST_REQUEST = "H55MATCH_LIST_REQUEST";
export const H55MATCH_LIST_SUCCESS = "H55MATCH_LIST_SUCCESS";
export const H55MATCH_LIST_FAIL = "H55MATCH_LIST_FAIL";
export const H55MATCH_LIST_RESET = "H55MATCH_LIST_RESET";

export const MEMBER_UPDATE_GAMEID_REQUEST = "MEMBER_UPDATE_GAMEID_REQUEST";
export const MEMBER_UPDATE_GAMEID_REQUEST_SUCCESS =
  "MEMBER_UPDATE_GAMEID_REQUEST_SUCCESS";
export const MEMBER_UPDATE_GAMEID_REQUEST_FAIL =
  "MEMBER_UPDATE_GAMEID_REQUEST_FAIL";

export const TEAM_DELETE_REQUEST = "TEAM_DELETE_REQUEST";
export const TEAM_DELETE_SUCCESS = "TEAM_DELETE_SUCCESS";
export const TEAM_DELETE_FAIL = "TEAM_DELETE_FAIL";

export const H55COSPLAY_LIST_REQUEST = "H55COSPLAY_LIST_REQUEST";
export const H55COSPLAY_LIST_SUCCESS = "H55COSPLAY_LIST_SUCCESS";
export const H55COSPLAY_LIST_FAIL = "H55COSPLAY_LIST_FAIL";

export const COSER_UPDATE_REQUEST = "COSER_UPDATE_REQUEST";
export const COSER_UPDATE_SUCCESS = "COSER_UPDATE_SUCCESS";
export const COSER_UPDATE_FAIL = "COSER_UPDATE_FAIL";
