export const ROLE_LIST_REQUEST = "ROLE_LIST_REQUEST";
export const ROLE_LIST_SUCCESS = "ROLE_LIST_SUCCESS";
export const ROLE_LIST_FAIL = "ROLE_LIST_FAIL";
export const ROLE_EDIT_REQUEST = "ROLE_EDIT_REQUEST";
export const ROLE_EDIT_SUCCESS = "ROLE_EDIT_SUCCESS";
export const ROLE_EDIT_FAIL = "ROLE_EDIT_FAIL";
export const ROLE_BY_ID_REQUEST = "ROLE_BY_ID_REQUEST";
export const ROLE_BY_ID_SUCCESS = "ROLE_BY_ID_SUCCESS";
export const ROLE_BY_ID_FAIL = "ROLE_BY_ID_FAIL";
export const ROLE_DELETE_REQUEST = "ROLE_DELETE_REQUEST";
export const ROLE_DELETE_SUCCESS = "ROLE_DELETE_SUCCESS";
export const ROLE_DELETE_FAIL = "ROLE_DELETE_FAIL";
export const RESOURCE_LIST_FAIL = "RESOURCE_LIST_FAIL";
export const RESOURCE_LIST_SUCCESS = "RESOURCE_LIST_SUCCESS";
export const RESOURCE_LIST_REQUEST = "RESOURCE_LIST_REQUEST";
export const RESOURCE_LIST_RESET = "RESOURCE_LIST_RESET";
export const RESOURCE_DELETE_REQUEST = "RESOURCE_DELETE_REQUEST";
export const RESOURCE_DELETE_SUCCESS = "RESOURCE_DELETE_SUCCESS";
export const RESOURCE_DELETE_FAIL = "RESOURCE_DELETE_FAIL";

export const RESOURCE_DETAILS_FAIL = "RESOURCE_DETAILS_FAIL";
export const RESOURCE_DETAILS_REQUEST = "RESOURCE_DETAILS_REQUEST";
export const RESOURCE_DETAILS_SUCCESS = "RESOURCE_DETAILS_SUCCESS";
export const RESOURCE_DETAILS_RESET = "RESOURCE_DETAILS_RESET";

export const RESOURCE_UPDATE_FAIL = "RESOURCE_UPDATE_FAIL";
export const RESOURCE_UPDATE_SUCCESS = "RESOURCE_UPDATE_SUCCESS";
export const RESOURCE_UPDATE_REQUEST = "RESOURCE_UPDATE_REQUEST";
export const RESOURCE_UPDATE_RESET = "RESOURCE_UPDATE_RESET";

export const RESOURCE_CREATE_FAIL = "RESOURCE_CREATE_FAIL";
export const RESOURCE_CREATE_SUCCESS = "  RESOURCE_CREATE_SUCCESS";
export const RESOURCE_CREATE_REQUEST = "  RESOURCE_CREATE_REQUEST";
export const RESOURCE_CREATE_RESET = "RESOURCE_CREATE_RESET";

export const PERMISSIONS_BY_ROLEID_REQUEST = "PERMISSIONS_BY_ROLEID_REQUEST";
export const PERMISSIONS_BY_ROLEID_SUCCESS = "PERMISSIONS_BY_ROLEID_SUCCESS";
export const PERMISSIONS_BY_ROLEID_FAIL = "PERMISSIONS_BY_ROLEID_FAIL";
export const PERMISSIONS_CREATE_FAIL = "PERMISSIONS_CREATE_FAIL";
export const PERMISSIONS_CREATE_SUCCESS = "PERMISSIONS_CREATE_SUCCESS";
export const PERMISSIONS_CREATE_REQUEST = "PERMISSIONS_CREATE_REQUEST";
export const PERMISSIONS_CREATE_RESET = "PERMISSIONS_CREATE_RESET";
