export const GAME_LIST_REQUEST = "GAME_LIST_REQUEST";
export const GAME_LIST_SUCCESS = "GAME_LIST_SUCCESS";
export const GAME_LIST_FAIL = "GAME_LIST_FAIL";

export const MENTOR_LIST_REQUEST = "MENTOR_LIST_REQUEST";
export const MENTOR_LIST_SUCCESS = "MENTOR_LIST_SUCCESS";
export const MENTOR_LIST_FAIL = "MENTOR_LIST_FAIL";

export const MENTOR_DETAILS_FAIL = "MENTOR_DETAILS_FAIL";
export const MENTOR_DETAILS_SUCCESS = "MENTOR_DETAILS_SUCCESS";
export const MENTOR_DETAILS_REQUEST = "MENTOR_DETAILS_REQUEST";
export const MENTOR_DETAILS_RESET = "MENTOR_DETAILS_RESET";

export const MENTOR_UPDATE_REQUEST = "MENTOR_UPDATE_REQUEST";
export const MENTOR_UPDATE_SUCCESS = "MENTOR_UPDATE_SUCCESS";
export const MENTOR_UPDATE_FAIL = "MENTOR_UPDATE_FAIL";
export const MENTOR_UPDATE_RESET = "MENTOR_UPDATE_RESET";

export const COURSE_REGISTER_LIST_REQUEST = "COURSE_REGISTER_LIST_REQUEST";
export const COURSE_REGISTER_LIST_SUCCESS = "COURSE_REGISTER_LIST_SUCCESS";
export const COURSE_REGISTER_LIST_FAIL = "COURSE_REGISTER_LIST_FAIL";

export const REGISTER_UPDATE_REQUEST = "REGISTER_UPDATE_REQUEST";
export const REGISTER_UPDATE_SUCCESS = "REGISTER_UPDATE_SUCCESS";
export const REGISTER_UPDATE_FAIL = "REGISTER_UPDATE_FAIL";
