export const SOCIALMEDIA_LIST_REQUEST = "SOCIALMEDIA_LIST_REQUEST";
export const SOCIALMEDIA_LIST_SUCCESS = "SOCIALMEDIA_LIST_SUCCESS";
export const SOCIALMEDIA_LIST_FAIL = "SOCIALMEDIA_LIST_FAIL";

export const CATEGORIES_LIST_REQUEST = "CATEGORIES_LIST_REQUEST";
export const CATEGORIES_LIST_SUCCESS = "CATEGORIES_LIST_SUCCESS";
export const CATEGORIES_LIST_FAIL = "CATEGORIES_LIST_FAIL";

export const CHANNEL_CREATE_REQUEST = "CHANNEL_CREATE_REQUEST";
export const CHANNEL_CREATE_SUCCESS = "CHANNEL_CREATE_SUCCESS";
export const CHANNEL_CREATE_FAIL = "CHANNEL_CREATE_FAIL";

export const CHANNEL_LIST_REQUEST = "CHANNEL_LIST_REQUEST";
export const CHANNEL_LIST_SUCCESS = "CHANNEL_LIST_SUCCESS";
export const CHANNEL_LIST_FAIL = "CHANNEL_LIST_FAIL";

export const CHANNEL_DETAILS_FAIL = "CHANNEL_DETAILS_FAIL";
export const CHANNEL_DETAILS_REQUEST = "CHANNEL_DETAILS_REQUEST";
export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_DETAILS_SUCCESS";
export const CHANNEL_DETAILS_RESET = "CHANNEL_DETAILS_RESET";

export const CHANNEL_UPDATE_FAIL = "CHANNEL_UPDATE_FAIL";
export const CHANNEL_UPDATE_SUCCESS = "CHANNEL_UPDATE_SUCCESS";
export const CHANNEL_UPDATE_REQUEST = "CHANNEL_UPDATE_REQUEST";
export const CHANNEL_UPDATE_RESET = "CHANNEL_UPDATE_RESET";

export const QUOTEITEMS_LIST_REQUEST = "QUOTEITEMS_LIST_REQUEST";
export const QUOTEITEMS_LIST_SUCCESS = "QUOTEITEMS_LIST_SUCCESS";
export const QUOTEITEMS_LIST_FAIL = "QUOTEITEMS_LIST_FAIL";

export const QUOTE_CREATE_REQUEST = "QUOTE_CREATE_REQUEST";
export const QUOTE_CREATE_SUCCESS = "QUOTE_CREATE_SUCCESS";
export const QUOTE_CREATE_FAIL = "QUOTE_CREATE_FAIL";

export const QUOTES_LIST_REQUEST = "QUOTES_LIST_REQUEST";
export const QUOTES_LIST_SUCCESS = "QUOTES_LIST_SUCCESS";
export const QUOTES_LIST_FAIL = "QUOTES_LIST_FAIL";

export const QUOTE_UPDATE_REQUEST = "QUOTE_UPDATE_REQUEST";
export const QUOTE_UPDATE_SUCCESS = "QUOTE_UPDATE_SUCCESS";
export const QUOTE_UPDATE_FAIL = "QUOTE_UPDATE_FAIL";
export const QUOTE_UPDATE_RESET = "QUOTE_UPDATE_RESET";

export const QUOTE_DELETE_REQUEST = "QUOTE_DELETE_REQUEST";
export const QUOTE_DELETE_SUCCESS = "QUOTE_DELETE_SUCCESS";
export const QUOTE_DELETE_FAIL = "QUOTE_DELETE_FAIL";

export const CHANNEL_TAGS_CREATE_REQUEST = "CHANNEL_TAGS_CREATE_REQUEST";
export const CHANNEL_TAGS_CREATE_SUCCESS = "CHANNEL_TAGS_CREATE_SUCCESS";
export const CHANNEL_TAGS_CREATE_FAIL = "CHANNEL_TAGS_CREATE_FAIL";

export const TAGS_LIST_REQUEST = "TAGS_LIST_REQUEST";
export const TAGS_LIST_SUCCESS = "TAGS_LIST_SUCCESS";
export const TAGS_LIST_FAIL = "TAGS_LIST_FAIL";

export const SOCIALDATA_CREATE_REQUEST = "SOCIALDATA_CREATE_REQUEST";
export const SOCIALDATA_CREATE_SUCCESS = "SOCIALDATA_CREATE_SUCCESS";
export const SOCIALDATA_CREATE_FAIL = "SOCIALDATA_CREATE_FAIL";

export const SOCIALDATA_LIST_REQUEST = "SOCIALDATA_LIST_REQUEST";
export const SOCIALDATA_LIST_SUCCESS = "SOCIALDATA_LIST_SUCCESS";
export const SOCIALDATA_LIST_FAIL = "SOCIALDATA_LIST_FAIL";

export const SOCIALDATA_UPDATE_REQUEST = "SOCIALDATA_UPDATE_REQUEST";
export const SOCIALDATA_UPDATE_SUCCESS = "SOCIALDATA_UPDATE_SUCCESS";
export const SOCIALDATA_UPDATE_FAIL = "SOCIALDATA_UPDATE_FAIL";
export const SOCIALDATA_UPDATE_RESET = "SOCIALDATA_UPDATE_RESET";

export const SOCIALDATA_DELETE_REQUEST = "SOCIALDATA_DELETE_REQUEST";
export const SOCIALDATA_DELETE_SUCCESS = "SOCIALDATA_DELETE_SUCCESS";
export const SOCIALDATA_DELETE_FAIL = "SOCIALDATA_DELETE_FAIL";

export const PRICING_LIST_REQUEST = "PRICING_LIST_REQUEST";
export const PRICING_LIST_SUCCESS = "PRICING_LIST_SUCCESS";
export const PRICING_LIST_FAIL = "PRICING_LIST_FAIL";
